twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        deneme: "sdgsdgsdg"
        htmlMeta:
            - key: "description"
              value: "Bişey"
            - key: "author"
              value: "UFuk"
when@test:
    twig:
        strict_variables: true
