controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: "/admin/dashboard"
    controller: App\Controller\AuthController::list


