controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

kernel:
    resource: ../src/Kernel.php
    type: annotation

default_index:
    path: /{_locale}/
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction

index:
    path: "/admin/dashboard"
    controller: App\Controller\AuthController::list
    requirements:
        _locale: '½app_locales½'
    defaults:
        template: admin/dashboard/index.html.twig
        _locale: '%locale%'


